var tipArray = [
  "Mystery Orbs could be built into items of Exalted quality. Exalted items have all their stats greatly improved. Exalted items are shareable and unsellable",
  "Experience from experience sources is not split between players, but instead is granted 100% each within range of effect. You still able to miss some by not being nearby.",
  "Kills made by friendly towers, lane creeps and friendly heroes will only grant 30% of the unit's gold bounty. Last hits are still the only way to get a full gold bounty.",
  "Bottom lane has it's own shop near the creep gather spot.",
  "Moonshards can be consumed infinite times.",
  "Buildings like towers and barracks could be upgraded using the Building Upgrade, available at the shop. Towers will get more  damage, armor, more useful auras and a splitshot ability. Upgrading barracks will increase friendly creeps damage, armor and their total amount allowed per lane. The upgrade will persist even if barracks get destroyed.",
  "Orb of Venom is a good starting item for ranged heroes with low attack damage. It deals 10 magical splash damage and is stackable.",
  "Losing towers or barracks to Horde makes enemy creeps stronger. Destroying Horde towers and barracks grants your team some useful buffs",
  "Upgraded Aether lens improves your cast range greatly.",
  "Willful Resonance deals part of player's attack damage as splash magic damage.",
  "Aghanim's Regalia provides great spell boost damage for a short time.",
  "Cursed Rapier provides great damage boost based on health, drained from it's user. It provides 20% resistance to all damage types, but reduces incoming healing by -35%",
  "Heart of Tarrasque is slightly changed. It breaks on creep attack, but still has some base health regeneration",
  "Horde Wand gains a charge for every creep, dying nearby the user. Charges, when consumed, restore some health and mana",
  "Dragon Javelins splits user's attacks in a barrage of javelins, dealing bonus damage to nearby enemies. Bonus attacks provided by Dragon Javelins won't apply modifiers like critical hits, lifesteal and etc.",
  "Wasp grants user an ability to gain flying movement for short period of time.",
  "Boots of Travel 3 provides user with an ability to teleport anywhere on the map",
  "Helm of Oppressor allows to dominate a non-boss, non-ancient creep anywhere on the map"];